spring:
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          batch_size: 100
        order_updates: true
        format_sql: true
        default_schema: java_17
  datasource:
    driver-class-name: org.postgresql.Driver
    password: pass
    username: postgres
    url: jdbc:postgresql://localhost:5432/versions_db
server:
  port: 9093